### ISSUE TITLE
WebPayment sample?

### ISSUE THREAD

**Issue by escarabin** [mehdirochdi/payline-sdk-laravel#1]
Hi!

May you please provide a sample on how to perform a payment? I have installed the package but I don't know how to use it.

Thanks in advance,

Emmanuel SCARABIN

**Comment by mehdirochdi** [comment]
Hi,
sorry if delayed to answer you, for the payment i use SDK PHP website payline
[http://www.payline.com/index.php/fr/](url)
you must have a demo account for testing payment and SDK
look at the file CONFIG.php in directory payline-sdk-laravel/src/Lib/CONFIG.php
you must have MERCHANT_ID, ACCESS_KEY
